# Generated by Django 4.0.4 on 2022-07-25 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_zikr_zikr_arabic_zikr_zikr_mean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('send', models.BooleanField(default=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('score', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('send', models.BooleanField(default=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('score', models.CharField(blank=True, max_length=500, null=True)),
                ('proekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.proekt')),
            ],
        ),
        migrations.DeleteModel(
            name='Zikr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='proekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.proekt'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user'),
        ),
    ]
