# Generated by Django 4.0.6 on 2022-08-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_askmoney_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='client',
            new_name='payment',
        ),
    ]
